options:
  git-repo:
    type: string
    default: ""
    description: "A git repository to clone for salt configurations"
  git-branch:
    type: string
    default: "master"
    description: "The branch to checkout"
  formula-path:
    type: string
    default: "/srv/salt/saltstack-formulas/"
    description: "Location for formula submodules to configure"
  use-dns:
    type: boolean
    default: True
    description: "If True master advertises it's hostanme, otherwise IP"

